import * as XLSX from "xlsx";
import type { AppState, Material, SearchResult } from "./types";

function inferSourceFromSupplier(supplier: string): string {
  const s = (supplier || "").toLowerCase();
  if (s.includes("addgene")) return "Addgene";
  if (s.includes("thermo")) return "Thermo Fisher";
  if (s.includes("sigma") || s.includes("merck")) return "Sigma-Aldrich";
  if (s.includes("promega")) return "Promega";
  if (s.includes("qiagen")) return "Qiagen";
  if (s.includes("idt")) return "IDT";
  if (s.includes("atcc")) return "ATCC";
  return "Other";
}

export function findSupplierUrl(supplier: string, item: string, sources: SearchResult[]): string {
  const s = (supplier || "").toLowerCase();
  const i = (item || "").toLowerCase().split(" ").filter((w) => w.length > 3);
  const match = sources.find((r) => {
    const u = r.url.toLowerCase();
    return s && u.includes(s.replace(/[^a-z0-9]/g, "").slice(0, 6));
  });
  if (match) return match.url;
  // fallback: any source whose title or content mentions the item word
  const fallback = sources.find((r) =>
    i.some((w) => r.title.toLowerCase().includes(w) || (r.content ?? "").toLowerCase().includes(w)),
  );
  return fallback?.url ?? "";
}

function autoWidth(rows: (string | number)[][]): { wch: number }[] {
  if (!rows.length) return [];
  const cols = rows[0].length;
  const widths: number[] = new Array(cols).fill(10);
  for (const row of rows) {
    row.forEach((cell, i) => {
      const len = String(cell ?? "").length;
      if (len > widths[i]) widths[i] = Math.min(60, len + 2);
    });
  }
  return widths.map((w) => ({ wch: w }));
}

export function exportToXLSX(state: AppState) {
  const date = new Date().toISOString().slice(0, 10);
  const wb = XLSX.utils.book_new();

  const allSupplierSources = [
    ...state.retrieval_results.supplierSources,
    ...state.retrieval_results.plasmidSources,
  ];

  // ── Sheet 1: Materials ─────────────────────────────
  const matsRaw: Material[] = state.experiment_plan.materials?.materials ?? [];
  const matsHeader = [
    "#",
    "Item Name",
    "Supplier",
    "Catalog Number",
    "Purpose in Experiment",
    "Quantity Estimate",
    "Confidence",
    "Product URL",
    "Source",
    "Notes",
  ];
  const matsRows = matsRaw.map((m, i) => {
    const url = findSupplierUrl(m.supplier, m.item_name, allSupplierSources);
    return [
      i + 1,
      m.item_name,
      m.supplier,
      m.catalog_number,
      m.purpose,
      m.quantity_estimate,
      m.confidence,
      url,
      inferSourceFromSupplier(m.supplier),
      "",
    ];
  });
  const summary = `Generated by LabMind on ${date} | Experiment: ${state.experiment_type ?? "—"} | Total items: ${matsRaw.length}`;
  const matsAoa: (string | number)[][] = [
    [summary, "", "", "", "", "", "", "", "", ""],
    matsHeader,
    ...matsRows,
  ];
  const wsMats = XLSX.utils.aoa_to_sheet(matsAoa);
  // hyperlink cells (column H = index 7), header is row 2 (index 1), data starts at row 3
  matsRows.forEach((row, idx) => {
    const url = row[7] as string;
    if (url) {
      const addr = XLSX.utils.encode_cell({ r: idx + 2, c: 7 });
      const cell = wsMats[addr];
      if (cell) cell.l = { Target: url, Tooltip: "Open supplier page" };
    }
  });
  wsMats["!cols"] = autoWidth(matsAoa);
  wsMats["!merges"] = [{ s: { r: 0, c: 0 }, e: { r: 0, c: 9 } }];
  XLSX.utils.book_append_sheet(wb, wsMats, "Materials");

  // ── Sheet 2: Budget ────────────────────────────────
  const budget = state.experiment_plan.budget;
  const budHeader = [
    "#",
    "Category",
    "Item",
    "Supplier",
    "Catalog Number",
    "Unit Cost (€)",
    "Quantity",
    "Total Line Cost (€)",
    "Confidence",
    "Supplier URL",
    "Notes",
  ];
  const budRows: (string | number)[][] = [];
  if (budget) {
    budget.budget_lines.forEach((l, i) => {
      const matchingMat = matsRaw.find((m) => m.item_name.toLowerCase().includes(l.item.toLowerCase().slice(0, 5)));
      const supplier = matchingMat?.supplier ?? "—";
      const cat = matchingMat?.catalog_number ?? "—";
      const url = matchingMat ? findSupplierUrl(supplier, l.item, allSupplierSources) : "";
      budRows.push([
        i + 1,
        l.category,
        l.item,
        supplier,
        cat,
        l.unit_cost,
        l.quantity,
        l.total,
        matchingMat?.confidence ?? "estimated",
        url,
        l.notes ?? "",
      ]);
    });
    budRows.push(["", "Materials subtotal", "", "", "", "", "", budget.subtotal_materials, "", "", ""]);
    budRows.push(["", "Operations subtotal", "", "", "", "", "", budget.subtotal_operations, "", "", ""]);
    budRows.push(["", "TOTAL", "", "", "", "", "", budget.total_estimated_cost, "", "", ""]);
  }
  const budAoa: (string | number)[][] = [budHeader, ...budRows];
  if (budget) {
    budAoa.push(["", "All costs are estimates. Confirm current prices with suppliers before ordering.", "", "", "", "", "", "", "", "", ""]);
  }
  const wsBud = XLSX.utils.aoa_to_sheet(budAoa);
  budRows.forEach((row, idx) => {
    const url = row[9] as string;
    if (url) {
      const addr = XLSX.utils.encode_cell({ r: idx + 1, c: 9 });
      const cell = wsBud[addr];
      if (cell) cell.l = { Target: url };
    }
  });
  wsBud["!cols"] = autoWidth(budAoa);
  XLSX.utils.book_append_sheet(wb, wsBud, "Budget");

  // ── Sheet 3: Procurement (To Order) ─────────────────
  const procHeader = ["Priority", "Item Name", "Suggested Supplier", "Action Required", "URL to search", "Notes"];
  const procRows: (string | number)[][] = matsRaw
    .filter((m) => m.confidence === "inferred" || !m.catalog_number || m.catalog_number === "—")
    .map((m) => [
      m.confidence === "inferred" ? "High" : "Medium",
      m.item_name,
      m.supplier,
      m.catalog_number ? "Confirm catalog number with supplier" : "Identify supplier and catalog number",
      `https://www.google.com/search?q=${encodeURIComponent(m.item_name + " " + m.supplier)}`,
      m.purpose,
    ]);
  const procAoa = [procHeader, ...(procRows.length ? procRows : [["—", "No items flagged for follow-up.", "", "", "", ""]])];
  const wsProc = XLSX.utils.aoa_to_sheet(procAoa);
  procRows.forEach((row, idx) => {
    const url = row[4] as string;
    if (url) {
      const addr = XLSX.utils.encode_cell({ r: idx + 1, c: 4 });
      const cell = wsProc[addr];
      if (cell) cell.l = { Target: url };
    }
  });
  wsProc["!cols"] = autoWidth(procAoa);
  XLSX.utils.book_append_sheet(wb, wsProc, "To Order");

  // ── Sheet 4: Sources ───────────────────────────────
  const sources: Array<{ type: string; r: SearchResult }> = [
    ...state.retrieval_results.protocolSources.map((r) => ({ type: "Protocol", r })),
    ...state.retrieval_results.literatureSources.map((r) => ({ type: "Literature", r })),
    ...state.retrieval_results.supplierSources.map((r) => ({ type: "Supplier", r })),
    ...state.retrieval_results.plasmidSources.map((r) => ({ type: "Plasmid", r })),
    ...state.retrieval_results.validationSources.map((r) => ({ type: "Validation", r })),
  ];
  const srcHeader = ["Type", "Title", "URL", "Relevance Note"];
  const srcRows: (string | number)[][] = sources.map(({ type, r }) => [
    type,
    r.title || "",
    r.url,
    (r.content ?? "").slice(0, 140),
  ]);
  const srcAoa = [srcHeader, ...(srcRows.length ? srcRows : [["—", "No sources retrieved.", "", ""]])];
  const wsSrc = XLSX.utils.aoa_to_sheet(srcAoa);
  srcRows.forEach((row, idx) => {
    const url = row[2] as string;
    if (url) {
      const addr = XLSX.utils.encode_cell({ r: idx + 1, c: 2 });
      const cell = wsSrc[addr];
      if (cell) cell.l = { Target: url };
    }
  });
  wsSrc["!cols"] = autoWidth(srcAoa);
  XLSX.utils.book_append_sheet(wb, wsSrc, "Sources");

  XLSX.writeFile(wb, `labmind_materials_budget_${date}.xlsx`);
}
